language: rust

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    # MSRV
    - rust: 1.31.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

branches:
  only:
    - master
    - staging
    - trying
